### ISSUE TITLE
Bug in example from 'Using ggfan to plot a distribution'

### ISSUE THREAD

**Issue by johnd85** [jasonhilton/ggfan#9]
Dear Jason,

I am somewhat new to R so please forgive me if the below issue is due to my ignorance.

I have copied the code for the first example in the vignette:

library(ggplot2)
library(magrittr)
library(tidyr)
library(dplyr)
library(ggfan)

# generate mean and variance for sequence of samples over time
N_time <- 50
N_sims <- 1000 
time <- 1:N_time
mu <- time**2 * 0.03 + time * 0.3
sds <- exp(time**2 * -0.001 + time * 0.1)

# simulate 1000 samples from each time point
fake_data <- sapply(time, function(i) rnorm(N_sims, mu[i], sds[i]))

# gather into a long-form, tidy dataset
fake_df <- data.frame(x=time, t(fake_data)) %>% gather(key=Sim, value=y, -x)
p <- ggplot(fake_df, aes(x=x,y=y)) + geom_interval()
print(p)

Attempting to run this, I get the following message:

Don't know how to automatically pick scale for object of type quosure/formula. Defaulting to continuous.
Don't know how to automatically pick scale for object of type quosure/formula. Defaulting to continuous.
Don't know how to automatically pick scale for object of type quosure/formula. Defaulting to continuous.
Error: A continuous variable can not be mapped to linetype

Your package is really cool, would love to get it working! Any help would be greatly appreciated.

Best regards,

John.

**Comment by jasonhilton** [comment]
Hi John, 

Thanks for filing this - I'm glad that you think the package might be useful!
I can't see that you are doing anything wrong and if I copy the code above, it seems to work on my machine ok at the moment, so I'm not sure what could be causing this.
Just to rule some things out, if possible, could you update all your existing packages, restart R, and try again? 
Most likely it's something to do with the version of some particular R package that is causing the problem. 
Additionally, could you post the results of `sessionInfo()` to help me narrow down the issue? 

Thanks, 
Jason

**Comment by johnd85** [comment]
Thanks, will do and will let you know results, unfortunately will likely be tomorrow as travelling and having Wi-Fi issues on laptop!

Best regards,

John.

**Comment by johnd85** [comment]
Dear Jason,

I updated my version of R and re-installed all packages, and now code is working perfectly.

Thank you very much for taking the time to help.

Best regards,

John.

**Comment by jasonhilton** [comment]
Fantastic - let me know if you encounter any other issues. :)
